vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.termguicolors = true
vim.env.NVIM_TUI_ENABLE_TRUE_COLOR = 1

vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.expandtab = false
vim.opt.tabstop = 2
vim.opt.smarttab = true
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.autoindent = true
vim.opt.listchars = 'tab:|\\ ,trail:▫'
vim.opt.list = true
vim.opt.scrolloff = 6
vim.opt.ttimeoutlen = 0
vim.opt.timeout = false
vim.opt.viewoptions = 'cursor,folds,slash,unix'
vim.opt.wrap = true
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.showmode = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
--vim.opt.visualbell = true
--vim.opt.colorcolumn = '120'
